### ISSUE TITLE
Consider logging the error more verbosely if the "heading" is set wrong

### ISSUE THREAD

**Issue by StylianosGakis** [iurysza/module-graph#1]
I was trying this out, and I misunderstood what "Heading" was from the `ModuleGraphExtension`, and thought maybe it'd be a title for the mermaid graph.
So I added a random name in there. This meant that inside `appendMermaidGraphToReadme` it was not finding the heading so it was hitting [this line](https://github.com/iurysza/module-graph/blob/f885011c48210e4e56507e3d41abd6edb3ad5ba4/plugin-build/modulegraph/src/main/kotlin/dev/iurysouza/modulegraph/MermaidGraph.kt#L102).
Running it by default, means that I do not get the `debug` errors, and I feel like this has a justified reason to be more than just `logger.debug`, maybe it should be an error instead.

What do you think?

p.s. I did figure out how it works afterwards, just thought the error would help with a good explanation of how the heading property as misused and how to use it properly

**Comment by iurysza** [comment]
Hey, thanks for the feedback!
I'll definitely look into this. I was thinking of either adding some default heading definition or improving the error logs.

I think we can go with your suggestion then.
