### ISSUE TITLE
Empty Graph is getting generated

### ISSUE THREAD

**Issue by anishakd4** [iurysza/module-graph#10]
## 🐛 Describe the bug
Empty Graph is getting generated each time.

### Dependency Diagram

```
```mermaid
%%{
  init: {
    'theme': 'neutral'
  }
}%%

graph LR


```

```

## Gradle Wrapper

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists



## 📱 Tech info
 - Android Studio Electric Eel | 2022.1.1 Patch 2
 - Mac OS: 13.3 (22E252)

**Comment by iurysza** [comment]
Hey! Can you please run `./gradlew projects` and post the output? 
Ty.

**Comment by anishakd4** [comment]
> Configure project :
Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'BintrayJCenter' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'MavenLocal' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven2' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven3' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven4' was added by build file 'build.gradle'

> Configure project :app
WARNING:The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
WARNING:The option 'android.enableR8' is deprecated.
It was removed in version 7.0 of the Android Gradle plugin.
Please remove it from `gradle.properties`.
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
Build was configured to prefer settings repositories over project repositories but repository 'maven5' was added by build file 'app/build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'Google2' was added by build file 'app/build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by build file 'app/build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'flatDir' was added by build file 'app/build.gradle'
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'androidx.annotation:annotation:1.0.0', 'com.github.bumptech.glide:compiler:4.8.0'.

> Task :projects

------------------------------------------------------------
Root project 'doorapp-consumer'
------------------------------------------------------------

Root project 'doorapp-consumer'
\--- Project ':app'

To see a list of the tasks of a project, run gradlew <project-path>:tasks
For example, try running gradlew :app:tasks

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

**Comment by iurysza** [comment]
It looks like you only have a single module:

```
--- Project ':app'
```

You need more modules for this plugin to be useful for you.
For instance, on [this project ](https://github.com/iurysza/livematch) I get this when running the same command: 
```
Project ':modules'
+--- Project ':modules:app'
|    +--- Project ':modules:app:main'
|    \--- Project ':modules:app:playground'
+--- Project ':modules:core'
|    +--- Project ':modules:core:common'
|    +--- Project ':modules:core:design-system'
|    +--- Project ':modules:core:footballdata'
|    \--- Project ':modules:core:reddit'
\--- Project ':modules:features'
     +--- Project ':modules:features:match-day'
     \--- Project ':modules:features:match-thread'
```
