### ISSUE TITLE
Empty generated graph

### ISSUE THREAD

**Issue by ferinagy** [iurysza/module-graph#15]
After applying the plugin (version 0.4.0) to our project, the `createModuleGraph` task runs successfully, but the created graph is empty. I have seen https://github.com/iurysza/module-graph/issues/10 and in our case `./gradlew projects` gives output of 100+ projects.

This is currently created graph:

````markdown
### Dependency Diagram

```mermaid
%%{
  init: {
    'theme': 'dark'
  }
}%%

graph TB


```
````

I tried looking into the issue a bit and it seems that the `parseProjectStructure()` method is called before the projects are configured, so `sourceProject.configurations` is empty at the time.

**Comment by iurysza** [comment]
Interesting!
The `parseProjectStructure()` call happens only when the `apply` method is called, but by this time the project configuration has already happened.

Can you maybe describe what your project looks like? 
For reference, I'm using this plugin on a multimodule project setup [here](https://github.com/iurysza/livematch/blob/main/modules/build.gradle.kts#L4). Perhaps it's useful for you to take a look and see what might be causing this.

**Comment by ferinagy** [comment]
I managed to track this down to this block in our root project:

```kotlin
allprojects {
    project.tasks.all {

    }
}
```

If I add it to the `sample` module, it also creates an empty graph. It appears to affect the order in which the projects are configured. Same seems to happen with the `--configure-on-demand` option.

**Comment by raamcosta** [comment]
I also had this issue and I tried commenting out all `allprojects` blocks from root build.gradle.kts file since these are only used to configure ktlint, detekt and other similar tools for all modules.

Once I did that, the plugin worked :) 
Hope that helps!
