### ISSUE TITLE
Use regex to exclude modules from graph

### ISSUE THREAD

**Issue by iurysza** [iurysza/module-graph#16]
## 💡 Describe the solution you'd like

Allows the user to set up regex patterns to exclude specific modules during graph generation. 

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by AndrazP** [comment]
My project contains a large number of modules. I could use this feature to remove those that are less important.
![image](https://github.com/iurysza/module-graph/assets/1963904/e567754b-76a2-4122-ac4f-b4a1cb77e90b)

**Comment by iurysza** [comment]
Gonna address this one soon ✌️
