### ISSUE TITLE
Add different color for different kinds of modules

### ISSUE THREAD

**Issue by raamcosta** [iurysza/module-graph#20]
## 💡 Describe the solution you'd like
I think a really cool feature would be to make a visual distinction between Android apps, Android libs, Kotlin/Jvm modules (maybe others related with KMP? 🤔 I feel these ones would be a good start though).

## 🤚 Do you want to develop this feature yourself?
I might look into it if I have time, but right now it's impossible. Between my own library, work, family, I'm totally booked 😬

**Comment by iurysza** [comment]
Cool idea! This can definitely be useful, especially when you're dealing with big projects. We got a couple of options here - change the ﻿`node` colors or the ﻿`edges`.

This could let folks personalize their node color settings. I mean, I was thinking of letting users pick a color for the ﻿nodes using a regex pattern. This would allow all `﻿something-feature` modules to show up in red. 

What do you think?

**Comment by raamcosta** [comment]
The regex option is good, but I feel like an option specifically for android apps / android libs / kotlin/jvm modules would still be nice in some cases. For example in our project, there's no naming convention that lets us know about this characteristic of the module.
I am assuming it isn't hard to know what kind of module it is? Maybe based on which plugins are applied? (agp app, agp lib, etc?).

**Comment by iurysza** [comment]
Hey @raamcosta , I've given this a try on #35 
It'd be nice to have your thoughts on the overall API and features.
