### ISSUE TITLE
Groovy DSL: Cannot set theme option

### ISSUE THREAD

**Issue by AndrazP** [iurysza/module-graph#32]
## 🐛 Describe the bug
Attempting to configure the `theme` option in Groovy DSL results in an error, whereas setting other options like `orientation` or `linkText` does not cause any issues.

## ⚠️ Current behavior
Build fails with error message: `Cannot set the value of extension 'moduleGraphConfig' property 'theme' of type dev.iurysouza.modulegraph.Theme using an instance of type java.lang.Class.`

## ✅ Expected behavior
`theme` can be configured.

## 💣 Steps to reproduce

```groovy
import dev.iurysouza.modulegraph.Theme

moduleGraphConfig {
    readmePath = "./README.md"
    heading = '### Dependency Diagram'
    theme = Theme.DEFAULT
}
```

**Comment by iurysza** [comment]
Thanks for the report! I'll work on a fix
