### ISSUE TITLE
Currently the graph is generated but can't view it on a bitbucket repository

### ISSUE THREAD

**Issue by joelkanyi** [iurysza/module-graph#42]

**Comment by iurysza** [comment]
Hey, the rendering part depends on the tool that you use to view the markdown file.

As I mentioned in the README:

> The raw code block automatically renders as a graph on [GitHub](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/), [Gitlab](https://about.gitlab.com/handbook/tools-and-tips/mermaid/#mermaid-diagrams), [Jetbrains IDEs](https://plugins.jetbrains.com/plugin/20146-mermaid) and [VSCode ](https://marketplace.visualstudio.com/items?itemName=MermaidChart.vscode-mermaid-chart).

[This](https://mermaid.js.org/ecosystem/integrations-community.html#official-integration) is a more comprehensive list.

But no, unfortunately there's still no Bitbucket support.
