### ISSUE TITLE
Tried adding to my project but did not work.

### ISSUE THREAD

**Issue by KaustubhPatange** [iurysza/module-graph#8]
I was trying to add this plugin to my [project](https://github.com/KaustubhPatange/Gear-VPN/) but it seems to be no luck. The task completes successfully (no error) but nothing is added to the Readme file.

Here's what I've done,

1. Added the plugin (legacy approach) Groovy DSL.
2. Configured the plugin,

```groovy
 moduleGraphConfig {
      readmePath = '$projectDir/test.md' // created this new file under root, seems like an output file parameter.
      heading = '### Dependency Diagram'
  }
```
3. Ran the gradle command as mentioned `./gradlew createModuleGraph`. The task completes successfully but produces no output i.e no change to `test.md` file.

----
Also, I was looking at the source code & it seems there is an additional configuration property `outputFile` but when I set it, it says no such property exists. Seems like the latest version is not published on the gradle plugins portal.

**Comment by axel-legue** [comment]
Hello, 
Same issue for me

**Comment by stephanepechard** [comment]
Hello,
Same issue for me too. I also had to create an empty `test.md` because I didn't change the path. I'd say the plugin could create the file if it does not exist.

**Comment by iurysza** [comment]
> My version used `readmePath = 'test.md'` to be sure not to have this problem, and I still have no result in the file. Could it be because the file is to high in the file hierarchy?

Hey @stephanepechard , can you please run `./gradlew projects` and post the output?

**Comment by emitchel** [comment]
Looks like you need to add the heading in your README for it to work. I expected to see errors after running the command, maybe it should throw an error for us to diagnose.

After adding the header in my README it worked! @KaustubhPatange @stephanepechard @axel-legue 

 https://github.com/iurysza/module-graph/blob/main/plugin-build/modulegraph/src/main/kotlin/dev/iurysouza/modulegraph/MermaidGraph.kt#L108

**Comment by iurysza** [comment]
@emitchel Oh shoot! That must be it. Sorry, I think the docs weren't clear and this UX is pretty bad after all.
I'll merge #9 and will include that in the next release.

I'll close it for now. Cheers 🤘
